apiVersion: v1
kind: PersistentVolume
metadata:
  name: miq-pv01
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/hild/src/oc/volumes
  persistentVolumeReclaimPolicy: Recycle
